# docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    working_dir: /app
    volumes:
      - $PWD:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=nestjs_db

  postgres:
    image: postgres:14
    container_name: postgres_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nestjs_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
